backend/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('recipe/', include('recipe.urls')),
]

backend/recipe/urls.py
from django.urls import path
from . import views


app_name = 'recipe'
urlpatterns = [
    path('search/', views.search, name="recipe"),
]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from recipe.models import Recipe


# Create your models here.
class CustomUser(AbstractUser):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.email

backend/recipe/models.py
from django.db import models

# Create your models here.


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    date_created = models.DateField(auto_now=True)

backend/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.core.exceptions import ValidationError


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2']

backend/recipe/forms.py
from django import forms


class SearchForm(forms.Form):
    search_input = forms.CharField(max_length=200)

backend/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as login_user
from .forms import RegisterForm
from .models import CustomUser

# Create your views here.


def home(request):
    return render(request, 'home.html', {})


def login(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = CustomUser.objects.get(username=form.cleaned_data['username'])
            login_user(request, user)
            return redirect('/')
    return render(request, 'login.html', {'form': form})


def signup(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'signup.html', {'form': form})

backend/recipe/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import SearchForm
from .models import Recipe
from serpapi import GoogleSearch


# Create your views here.
@login_required
def search(request):
    form = SearchForm()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['search_input']

            params = {
                "api_key": "e44dc59698bfd057e179e9f9cf8c58a2b9ebf833ab44c7490dfc2244035dc8b8",
                "engine": "google",
                "q": query,
                "google_domain": "google.com",
                "gl": "us",
                "hl": "en",
                "device": "desktop"
            }

            search = GoogleSearch(params)
            results = search.get_dict()
            recipies = results['recipes_results'][0]
            recipe = Recipe(title=recipies['title'], website=recipies['link'])
            recipe.save()
    return render(request, 'search.html', {'form': form})

backend/templates/base.html
<!-- please add background img in css -->
{% load static %}
<head>
    {% block head %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<div class="App" id="App">
    <div class="HomeBox">
        <a href="{% url 'accounts:home' %}" class="ImgLink"><img src="{% static 'img/freshly-logo.png' %}" alt="Freshly Logo"/></a>
        {% block content %}{% endblock %}
    </div>
</div>

backend/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/App.css' %}">
{% endblock %}
{% block content %}
<div class="Head">
    <h3 style="font-size: 3.5vw">Welcome to Freshly</h3>
</div>
<div class="SecondHead">
    <h3 style="font-size: 1.5vw">We strive to ensure that everyone has a <br></br> well-balanced, natural diet with just the <br></br>ingredients at hand.</h3>
</div>
<div class="HomeLoginButton">
  <a href="/login">
    <button>LOGIN</button>
  </a>
</div>
<div class="HomeSignUpButton">
    <a href="/signup">
        <button>SIGN UP</button>
    </a>
</div>
{% endblock %}

backend/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/App.css' %}">
<link rel="stylesheet" href="{% static 'css/Login.css' %}">
<link rel="stylesheet" href="{% static 'css/Signup.css' %}">
{% endblock %}
{% block content %}
<div class="LoginHeader">
    <h3>Login</h3>
</div>
<form method="post" class="LoginInputText">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="LoginReadyButton">Login</button>
</form>
{% endblock %}

backend/templates/search.html
{% load static %}
{% load crispy_forms_tags %}
<head>
<link rel="stylesheet" href="{% static 'css/Search.css' %}">
</head>
<body>
<div id="SearchPage" style="background-image: url(https://cdn.discordapp.com/attachments/893663423164989440/896574382498000916/image0.png)">
    <div>
        <h3 className="SearchPageHeader">Freshly</h3>
    </div>
    <div>
        <label>Search Recipe:</label>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Search</button>
    </form>
</div>
</body>

backend/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/App.css' %}">
<link rel="stylesheet" href="{% static 'css/Signup.css' %}">
{% endblock %}
{% block content %}
    <div class="SignUpHeader">
        <h3 style="font-size: 3.5vw;">Sign Up</h3>
    </div>
<form class="RegisterForm" method="post">
    <!--<label style="grid-area: 1 / 1 / span 1 / span 7;">Enter an email:</label>
    <input style="grid-area: 1 / 1 / span 1 / span 12;" type="text" name="email"/>
    <label style="grid-area: 3 / 1 / span 1 / span 7;">Confirm email:</label>
    <input style="grid-area: 4 / 1 / span 1 / span 12;" type="text" name="email"/>
    <label style="grid-area: 6 / 1 / span 1 / span 7;">Enter a password:</label>
    <input style="grid-area: 7 / 1 / span 1 / span 12;" type="password" name="password"/>
    <label style="grid-area: 9 / 1 / span 1 / span 7;">Confirm password:</label>
    <input style="grid-area: 10 / 1 / span 1 / span 12;" type="password" name="confirm-password"/>
    <button style="grid-area: 11 / 5 / span 4 / span 4;" type="submit">READY?</button>-->
    {% csrf_token %}
    {{ form|crispy }}
    <br/>
    <button type="submit">READY?</button>
</form>
{% endblock %}